DROP DATABASE mainDB;

CREATE DATABASE mainDB;

USE mainDB;

CREATE TABLE users(
userid INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
uname VARCHAR(30) NOT NULL,
phash VARCHAR(40) NOT NULL,
salt VARCHAR(40),
email VARCHAR(60),
utype VARCHAR(20)
);

CREATE TABLE registeredBoats(
boatid INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userid INT(7) NOT NULL,
boat_type VARCHAR(40) NOT NULL,
area VARCHAR(40),
tel_num VARCHAR(20),
file_path VARCHAR(150)
);

CREATE TABLE incidents(id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY, itype INT(2), lat FLOAT(9,6),lon FLOAT(9,6));
