DROP DATABASE mainDB;

CREATE DATABASE mainDB;

USE mainDB;

CREATE TABLE users(
userid INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
uname VARCHAR(30) NOT NULL,
phash VARCHAR(40) NOT NULL,
salt VARCHAR(40),
email VARCHAR(60),
utype VARCHAR(20)
);
